### ISSUE TITLE
Infinite loop if you don't read cells

### ISSUE THREAD

**Issue by danvk** [vslinko/deno-csv#1]
I tried a small variation on the example in the README to try and get a sense for how fast this is. If you don't iterate over the columns, it goes into an infinite loop.

```ts
import { readCSV } from "https://deno.land/x/csv/mod.ts";

const f = await Deno.open(Deno.args[0]);

let n = 0;
for await (const row of readCSV(f)) {
  n++;
}
console.log('Read', n, 'lines');

f.close();
```

```
$ deno run --allow-read csvtest.ts test.csv
Compile file:///Users/danvk/github/deno-play/csvtest.ts
^C
```

My CSV file looks like this:

```
A,B,C
1,2,3
4,5,6
```

**Comment by vslinko** [comment]
Hello @danvk and thank you for your feedback!

I've fixed it by [this](https://github.com/vslinko/deno-csv/commit/89972e364b702c3a580b18e2a04fc426beef0da6) commit.
Now line will be read till end even you skipped that part.

**Comment by vslinko** [comment]
@danvk FYI currently deno-csv should be very slow because it based on ES generators and not optimised yet, but I'm going to optimise it soon.

**Comment by vslinko** [comment]
Benchmarked against https://csv.js.org/parse/:
```
deno run --allow-env --allow-read --allow-hrtime deno-csv.ts 500000-Records.csv
Read 500001 lines for 129.153099794 seconds
node npm-csv-parse.js 500000-Records.csv
Read 500001 lines for 8.543203381 seconds
```

**Comment by vslinko** [comment]
@danvk I've released some optimisations https://github.com/vslinko/deno-csv#benchmarks

**Comment by danvk** [comment]
Thanks @vslinko, that is definitely an improvement!

The generally slow speed of async iteration in Node has always been a pet peeve of mine, see this post from a few years back: [Async iterators: These Promises Are Killing My Performance!][2].

The good news is that things have gotten considerably faster from node 8 → 10 → 12. I have a repo with some benchmarks and sample numbers for a 32MB CSV file [here][2].

On my machine, Python's CSV reader reads that file in ~0.93s:

    $ python3.7 csv_reader.py
    Read 549996 lines, 4949964 cells in 0.936364 s

deno-csv takes ~5s, so it's slower but within an order of magnitude:

    $ deno run --allow-read --allow-hrtime csvtest.ts ~/github/async-iteration/stop_times.txt
    Read 549997 lines in 4825.432208 ms

The off-by-one error is concerning — I think it yields a blank line at the end of the file.

[1]: https://github.com/danvk/async-iteration/#results
[2]: https://medium.com/netscape/async-iterators-these-promises-are-killing-my-performance-4767df03d85b
