### ISSUE TITLE
inscrutable error

### ISSUE THREAD

**Issue by peetklecha** [vslinko/deno-csv#10]
hello,

when trying to parse the CSV found here: https://www.bls.gov/cew/classifications/areas/county-msa-csa-crosswalk.htm

i encounter this error: 

```
Error: Expected EOF, COLUMN_SEPARATOR, LINE_SEPARATOR; received 
    at CSVReader.parseCycle (https://deno.land/x/csv@v0.6.0/reader.ts:334:13)
```

but there's no indication where the error is in the CSV. it works fine for an abridged version consisting of only the first three lines of the file. it's a big file (3000+ rows) so exhaustively retrying larger and larger substrings of the original file would be quite tedious. at a minimum, giving a line or column number for the error would be very helpful.

(and for what it's worth, my IDE CSV extension doesn't detect any errors in the file, so the error itself may be erroneous.)

**Comment by vslinko** [comment]
@peetklecha Hi! Thank you for your feedback!

Added position information in https://github.com/vslinko/deno-csv/releases/tag/v0.7.0

**Comment by vslinko** [comment]
Could you send me that CSV for debugging?
I get "Access Denied" on https://www.bls.gov/cew/classifications/areas/county-msa-csa-crosswalk.htm

**Comment by peetklecha** [comment]
thank you @vslinko!!

and here you go. and for the record, i ended up solving the error by copying the content of the file into a new blank .csv, and it worked -- so no idea still what the error ever was! 

[qcew-county-msa-csa-crosswalk-csv.csv](https://github.com/vslinko/deno-csv/files/7403167/qcew-county-msa-csa-crosswalk-csv.csv)

**Comment by vslinko** [comment]
looks like your file using `\r\n` line separator instead of default `\n`. you can configure line separator manually https://github.com/vslinko/deno-csv#read-csv-file-with-custom-separators
