### ISSUE TITLE
Immediate Errors on Import

### ISSUE THREAD

**Issue by jeff-hykin** [vslinko/deno-csv#12]
~~I believe this is caused having unpinned dependencies on std lib imports~~
https://githubmemory.com/repo/denoland/deno/issues/10799

Well after checking source it looks like they are pinned. Is deno-csv incompatible with Deno 1.10?

<img width="827" alt="Screen Shot 2021-12-11 at 9 04 58 PM" src="https://user-images.githubusercontent.com/17692058/145698630-2f19ee97-f258-40a7-a553-708e8d0d439a.png">

**Comment by vslinko** [comment]
Unfortunately I can't reproduce the issue. Everything is working at least with deno 1.15 and 1.16.
Could you please update deno to 1.16 and try again? Or try `https://deno.land/x/csv@v0.5.1/mod.ts` instead of the latest version.

**Comment by jeff-hykin** [comment]
@vslinko Yeah it's definitely a Deno version error, there was talk of support for these errors/features in 1.12 I believe.

Sadly 1.11 is the newest I can get with my build system (nixpkg). 

5.1 does work and I ended up using that for my application and it seems to work well, so I suppose that's the solution.
