### ISSUE TITLE
parser hangs on double quotes in a value

### ISSUE THREAD

**Issue by ralyodio** [vslinko/deno-csv#15]
this row cannot be parsed:

`21115,Kyoto Ryokan "The KINOE",-1,35.00085,135.77732`

I believe it's the double quotes. How do I account for this?

**Comment by vslinko** [comment]
@ralyodio Hi!

This is invalid CSV according to RFC 4180:

> Fields containing line breaks (CRLF), double quotes, and commas should be enclosed in double-quotes.

I've improved error handling for this case in https://github.com/vslinko/deno-csv/releases/tag/v0.7.5.

So you have two options: fix the quotes in the source file or change `quote` parameter from double quotes to anything else:

```ts
for await (
  const row of readCSVRows(
    new StringReader('21115,Kyoto Ryokan "The KINOE",-1,35.00085,135.77732\n'),
    {
      quote: "'",
    },
  )
) {
  console.log(row);
}
```
