### ISSUE TITLE
[Feature Request] Read from line x to line y

### ISSUE THREAD

**Issue by artze** [vslinko/deno-csv#17]
When reading a csv file, we sometimes only want a subset of rows. I'd like to suggest for `readCSVRows` and `readCSVObjects` to expose options to read from a specified line number until a specified line number.

For reference, the `csv` npm has similar features (see below). The same API options could work for this lib, IMO.

- `from_line`: https://csv.js.org/parse/options/from_line/
- `to_line`: https://csv.js.org/parse/options/to_line

Keen to know what you think :)

**Comment by vslinko** [comment]
Hi @artze . Implemented in https://github.com/vslinko/deno-csv/releases/tag/v0.8.0

**Comment by vslinko** [comment]
Thank you for the feedback!

**Comment by artze** [comment]
Wow nice! :rocket:
