### ISSUE TITLE
Cannot read only the first line

### ISSUE THREAD

**Issue by atrahy** [vslinko/deno-csv#19]
Hello,

First, thank you for maintaining this package !

I just encounter a problem because I wanted to read only the first line of my file to parse the header but the option `toLine: 0` is override by the default option in the CSVReader class to read the entire file. 

This code will retrieve all the lines while my intention is to read only the first line.
```
const readIterable = readCSV(file, {
    fromLine: 0,
    toLine: 0,
  });
```

I think the solution could be a stronger check the the `toLine` option and check null / undefined / negative values instead of just the `||`.

Do you accept pull requests for changes ?

**Comment by vslinko** [comment]
@atrahy Hi, Thank you for the feedback!

Yes, it would be nice if you would make PR with the fix.
