### ISSUE TITLE
"@std/io/iterate-reader" not in import map

### ISSUE THREAD

**Issue by pasha-bolokhov** [vslinko/deno-csv#27]
A new compilation error, should be super easy to fix

```
error: Relative import path "@std/io/iterate-reader" not prefixed with / or ./ or ../ and not in import map from "https://deno.land/x/csv@v1.0.2/reader.ts"
    at https://deno.land/x/csv@v1.0.2/reader.ts:6:31
```

**Comment by 9oelM** [comment]
Same problem. How do we get around this issue?

**Comment by vslinko** [comment]
hi! thank you for feedback, but I can't reproduce the issue. could you please create a sample project with the issue?

**Comment by pasha-bolokhov** [comment]
This is a short as it is:
```typescript
import {
 readCSVObjects,
 writeCSVObjects,
} from "https://deno.land/x/csv@v1.0.2/mod.ts";
```

Running on `Deno` of a few latest versions, including 1.44.4 and 1.45.2

Perhaps we should switch all imports to `jsr`?

**Comment by vslinko** [comment]
yes, looks like it's impossible to import jsr modules via http https://jsr.io/docs/migrate-x-to-jsr#https-modules-supported-in-deno-not-in-jsr-packages

please, use `deno add @vslinko/csv` and replace all imports to `import {} from 'jsr:@vslinko/csv'`
