### ISSUE TITLE
Upgrade to Deno 1.2.0 and stdlib 0.61.0

### ISSUE THREAD

**Issue by shah** [vslinko/deno-csv#5]
Hi, this is a great library and I'm looking forward to using it with Deno 1.2.0 and stdlib 0.61.0 but it's breaking due to pinning of stdlib 0.52.0. I was curious if the library can be upgraded to the latest Deno and stdlib? Thanks!

**Comment by vslinko** [comment]
Hi @shah! Thanks for your notification about deno updates.

Deno 1.2.0 and stdlib 0.61.0 support pushed to master and released in v0.4.0.

**Comment by shah** [comment]
Awesome, thanks @vslinko!
